#!/bin/bash
export NODE_ENV=production

# If there is a grunt file, run $ grunt prod
if [ -f "${OPENSHIFT_REPO_DIR}"/gulpfile.js ]; then
    (cd "${OPENSHIFT_REPO_DIR}"; node_modules/gulp/bin/gulp )
fi